# Generated by Django 5.1.4 on 2025-02-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='line',
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='notes', to='yachay.tag'),
        ),
        migrations.AddField(
            model_name='note',
            name='line',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='yachay.line'),
        ),
    ]
