# Generated by Django 5.1.4 on 2025-02-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachay', '0004_alter_note_line_alter_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='yachay.author'),
        ),
        migrations.AlterField(
            model_name='notelink',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='next_notes', to='yachay.note'),
        ),
        migrations.AlterField(
            model_name='notelink',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previous_notes', to='yachay.note'),
        ),
    ]
