# Generated by Django 5.1.2 on 2025-02-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yachay', '0005_note_author_alter_notelink_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='line',
        ),
        migrations.RemoveField(
            model_name='note',
            name='code',
        ),
        migrations.DeleteModel(
            name='Line',
        ),
    ]
